name: Upload to OneDrive
description: Upload a file to OneDrive

inputs:
  client-id:
    required: true

  client-secret:
    required: true

  onedrive-path:
    required: true

  path:
    required: true

  refresh-token:
    required: true

runs:
  using: composite
  steps:
    - id: get-access-token
      name: Get access token
      run: |
        set +H

        ACCESS_TOKEN=$(curl \
          --data "client_id=${{ inputs.client-id }}" \
          --data "client_secret=${{ inputs.client-secret }}" \
          --data "refresh_token=${{ inputs.refresh-token }}" \
          --data "scope=https://graph.microsoft.com/.default" \
          --data "grant_type=client_credentials" \
          "https://login.microsoftonline.com/consumers/oauth2/v2.0/token" | jq -r '.access_token')

        echo "access-token=$ACCESS_TOKEN" >> $GITHUB_OUTPUT
      shell: bash

    - name: Upload
      run: |
        set +H

        curl \
          --header "Authorization: Bearer ${{ steps.get-access-token.outputs.access-token }}" \
          --header "Content-Type: application/octet-stream" \
          --upload-file "${{ inputs.path }}" \
          "https://graph.microsoft.com/v1.0/me/drive/root:${{ inputs.onedrive-path }}:/content"
      shell: bash
