name: Manual upload to OneDrive
description: Upload a file to OneDrive manually

inputs:
  api-endpoint:
    default: https://api.onedrive.com/v1.0

  client-id:
    required: true

  client-secret:
    required: true

  conflict-behavior:
    default: rename
    description: Either "rename", "fail" or "replace"

  path:
    required: true

  refresh-token:
    required: true

  tenant-id:
    default: consumers
    description: Tenant ID, use "consumers" for OneDrive Personal

outputs:
  created-date-time:
    value: ${{ steps.upload-file.outputs.created-date-time }}

  ctag:
    value: ${{ steps.upload-file.outputs.ctag }}

  etag:
    value: ${{ steps.upload-file.outputs.etag }}

  item-id:
    value: ${{ steps.upload-file.outputs.item-id }}

  quick-xor-hash:
    value: ${{ steps.upload-file.outputs.quick-xor-hash }}

  url:
    value: ${{ steps.upload-file.outputs.url }}

runs:
  using: composite
  steps:
    - id: get-access-token
      name: Get access token
      run: |
        CLIENT_ID=$(cat <<'EOF'
        ${{ inputs.client-id }}
        EOF
        )

        CLIENT_SECRET=$(cat <<'EOF'
        ${{ inputs.client-secret }}
        EOF
        )

        REFRESH_TOKEN=$(cat <<'EOF'
        ${{ inputs.refresh-token }}
        EOF
        )

        ACCESS_TOKEN=$(curl \
          --data "client_id=$CLIENT_ID" \
          --data "client_secret=$CLIENT_SECRET" \
          --data "refresh_token=$REFRESH_TOKEN" \
          --data "grant_type=refresh_token" \
          --fail-with-body \
          "https://login.microsoftonline.com/${{ inputs.tenant-id }}/oauth2/v2.0/token" | jq -r '.access_token')

        echo "access-token=$ACCESS_TOKEN" >> $GITHUB_OUTPUT
        echo "::add-mask::$ACCESS_TOKEN"
      shell: bash

    - name: Install jq
      run: sudo apt install jq
      shell: bash

    - id: get-upload-folder
      name: Get upload folder
      run: |
        ACCESS_TOKEN=$(cat <<'EOF'
        ${{ steps.get-access-token.outputs.access-token }}
        EOF
        )

        API_ENDPOINT=$(cat <<'EOF'
        ${{ inputs.api-endpoint }}
        EOF
        )

        FOLDER_ITEM_ID=$(curl \
          --fail-with-body \
          --header "Authorization: Bearer $ACCESS_TOKEN" \
          "$API_ENDPOINT/drive/special/approot" | jq -r .id)

        echo "folder-item-id=$FOLDER_ITEM_ID" | tee --append $GITHUB_OUTPUT
      shell: bash

    - id: upload-file
      name: Upload file
      run: |
        ACCESS_TOKEN=$(cat <<'EOF'
        ${{ steps.get-access-token.outputs.access-token }}
        EOF
        )

        API_ENDPOINT=$(cat <<'EOF'
        ${{ inputs.api-endpoint }}
        EOF
        )

        CONFLICT_BEHAVIOR=${{ inputs.conflict-behavior }}

        FILE_PATH=$(cat <<'EOF'
        ${{ inputs.path }}
        EOF
        )

        FOLDER_ITEM_ID=$(cat <<'EOF'
        ${{ steps.get-upload-folder.outputs.folder-item-id }}
        EOF
        )

        FILENAME="${FILE_PATH##*/}"
        FILE_SIZE=$(stat -c%s "$FILE_PATH")

        FILE_SIZE_MINUS_ONE=$((FILE_SIZE - 1))

        CREATE_UPLOAD_SESSION_JSON=$(jq \
          -n \
          --arg conflictBehavior "$CONFLICT_BEHAVIOR" \
          --arg filename "$FILENAME" \
          '{item:{ "@microsoft.graph.conflictBehavior": $conflictBehavior, name: $filename}}'
        )

        echo $CREATE_UPLOAD_SESSION_JSON | jq

        UPLOAD_URL=$(curl \
          --fail-with-body \
          --header "Authorization: Bearer $ACCESS_TOKEN" \
          --json "$CREATE_UPLOAD_SESSION_JSON" \
          "$API_ENDPOINT/drive/items/$FOLDER_ITEM_ID:/$FILENAME:/createUploadSession" | jq -r .uploadUrl
        )

        curl \
          --fail-with-body \
          --header "Content-Length: $FILE_SIZE" \
          --header "Content-Range: bytes 0-$FILE_SIZE_MINUS_ONE/$FILE_SIZE" \
          --upload-file "$FILE_PATH" \
          "$UPLOAD_URL" | tee --append curl.json

        CREATED_DATE_TIME=$(cat curl.json | jq -r .createdDateTime)
        CTAG=$(cat curl.json | jq -r .cTag)
        ETAG=$(cat curl.json | jq -r .eTag)
        ITEM_ID=$(cat curl.json | jq -r .id)
        QUICK_XOR_HASH=$(cat curl.json | jq -r .file.hashes.quickXorHash)
        WEB_URL=$(cat curl.json | jq -r .webUrl)

        echo "created-date-time=$CREATED_DATE_TIME" | tee --append $GITHUB_OUTPUT
        echo "ctag=$CTAG" | tee --append $GITHUB_OUTPUT
        echo "etag=$ETAG" | tee --append $GITHUB_OUTPUT
        echo "item-id=$ITEM_ID" | tee --append $GITHUB_OUTPUT
        echo "quick-xor-hash=$QUICK_XOR_HASH" | tee --append $GITHUB_OUTPUT
        echo "url=$WEB_URL" | tee --append $GITHUB_OUTPUT
      shell: bash
