name: Upload to OneDrive
description: Upload a file to OneDrive

inputs:
  api-endpoint:
    default: https://api.onedrive.com/v1.0

  client-id:
    required: true

  client-secret:
    required: true

  conflict-behavior:
    default: rename
    description: Either "rename", "fail" or "replace"

  path:
    required: true

  refresh-token:
    required: true

runs:
  using: composite
  steps:
    - id: get-access-token
      name: Get access token
      run: |
        set +H

        ACCESS_TOKEN=$(curl \
          --data "client_id=${{ inputs.client-id }}" \
          --data "client_secret=${{ inputs.client-secret }}" \
          --data "refresh_token=${{ inputs.refresh-token }}" \
          --data "grant_type=refresh_token" \
          --fail-with-body \
          "https://login.microsoftonline.com/consumers/oauth2/v2.0/token" | jq -r '.access_token')

        echo "access-token=$ACCESS_TOKEN" >> $GITHUB_OUTPUT
        echo "::add-mask::$ACCESS_TOKEN"
      shell: bash

    - name: Install tools
      run: sudo apt install jq
      shell: bash

    - name: Upload
      run: |
        set +H

        ACCESS_TOKEN=${{ steps.get-access-token.outputs.access-token }}
        API_ENDPOINT=${{ inputs.api-endpoint }}
        CONFLICT_BEHAVIOR=${{ inputs.conflict-behavior }}
        FILE_PATH=${{ inputs.path }}

        FILENAME="${FILE_PATH##*/}"
        FILE_SIZE=$(stat -c%s "$FILE_PATH")
        FILE_SIZE_MINUS_ONE=$((FILE_SIZE - 1))

        UPLOADING_FOLDER_ITEMID=$(curl \
          --fail-with-body \
          --header "Authorization: Bearer $ACCESS_TOKEN" \
          "$API_ENDPOINT/drive/special/approot" | jq -r .id)

        echo Item ID of uploading folder is $UPLOADING_FOLDER_ITEMID.

        CREATE_UPLOAD_SESSION_JSON=$(jq \
          -n \
          --arg conflictBehavior "$CONFLICT_BEHAVIOR" \
          --arg filename "$FILENAME" \
          '{item:{ "@microsoft.graph.conflictBehavior": $conflictBehavior, name: $filename}}'
        )

        echo Upload session URL dump
        echo $CREATE_UPLOAD_SESSION_JSON | jq

        UPLOAD_URL=$(curl \
          --fail-with-body \
          --header "Authorization: Bearer $ACCESS_TOKEN" \
          --json "$CREATE_UPLOAD_SESSION_JSON" \
          "$API_ENDPOINT/drive/items/$UPLOADING_FOLDER_ITEMID:/$FILENAME:/createUploadSession" | jq -r .uploadUrl)

        echo Upload URL is $UPLOAD_URL.

        curl \
          --fail-with-body \
          --header "Content-Length: $FILE_SIZE" \
          --header "Content-Range: bytes 0-$FILE_SIZE_MINUS_ONE/$FILE_SIZE" \
          --upload-file "$FILE_PATH" \
          "$UPLOAD_URL"
      shell: bash
